/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GlobalEngagementsRouteImport } from './routes/global-engagements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatWeDoIndexRouteImport } from './routes/what-we-do/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WhatWeDoSlugRouteImport } from './routes/what-we-do/$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries/$slug'
import { Route as EcosystemRethinkCarbonRouteImport } from './routes/ecosystem/rethink-carbon'
import { Route as EcosystemProjectDevelopmentRouteImport } from './routes/ecosystem/project-development'
import { Route as EcosystemInHouseAgentsRouteImport } from './routes/ecosystem/in-house-agents'
import { Route as EcosystemEnergyTransitionWorkforceRouteImport } from './routes/ecosystem/energy-transition-workforce'
import { Route as EcosystemEnergySectorIntelligenceRouteImport } from './routes/ecosystem/energy-sector-intelligence'
import { Route as EcosystemDigitalMrvPlatformsRouteImport } from './routes/ecosystem/digital-mrv-platforms'
import { Route as EcosystemDigitalMrvRouteImport } from './routes/ecosystem/digital-mrv'
import { Route as EcosystemAgriTechSolutionsRouteImport } from './routes/ecosystem/agri-tech-solutions'
import { Route as EcosystemAdvisoryHouseRouteImport } from './routes/ecosystem/advisory-house'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalEngagementsRoute = GlobalEngagementsRouteImport.update({
  id: '/global-engagements',
  path: '/global-engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoIndexRoute = WhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const WhatWeDoSlugRoute = WhatWeDoSlugRouteImport.update({
  id: '/what-we-do/$slug',
  path: '/what-we-do/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRethinkCarbonRoute = EcosystemRethinkCarbonRouteImport.update({
  id: '/ecosystem/rethink-carbon',
  path: '/ecosystem/rethink-carbon',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemProjectDevelopmentRoute =
  EcosystemProjectDevelopmentRouteImport.update({
    id: '/ecosystem/project-development',
    path: '/ecosystem/project-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcosystemInHouseAgentsRoute = EcosystemInHouseAgentsRouteImport.update({
  id: '/ecosystem/in-house-agents',
  path: '/ecosystem/in-house-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemEnergyTransitionWorkforceRoute =
  EcosystemEnergyTransitionWorkforceRouteImport.update({
    id: '/ecosystem/energy-transition-workforce',
    path: '/ecosystem/energy-transition-workforce',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcosystemEnergySectorIntelligenceRoute =
  EcosystemEnergySectorIntelligenceRouteImport.update({
    id: '/ecosystem/energy-sector-intelligence',
    path: '/ecosystem/energy-sector-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcosystemDigitalMrvPlatformsRoute =
  EcosystemDigitalMrvPlatformsRouteImport.update({
    id: '/ecosystem/digital-mrv-platforms',
    path: '/ecosystem/digital-mrv-platforms',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcosystemDigitalMrvRoute = EcosystemDigitalMrvRouteImport.update({
  id: '/ecosystem/digital-mrv',
  path: '/ecosystem/digital-mrv',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemAgriTechSolutionsRoute =
  EcosystemAgriTechSolutionsRouteImport.update({
    id: '/ecosystem/agri-tech-solutions',
    path: '/ecosystem/agri-tech-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const EcosystemAdvisoryHouseRoute = EcosystemAdvisoryHouseRouteImport.update({
  id: '/ecosystem/advisory-house',
  path: '/ecosystem/advisory-house',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/global-engagements': typeof GlobalEngagementsRoute
  '/impact': typeof ImpactRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ecosystem/advisory-house': typeof EcosystemAdvisoryHouseRoute
  '/ecosystem/agri-tech-solutions': typeof EcosystemAgriTechSolutionsRoute
  '/ecosystem/digital-mrv': typeof EcosystemDigitalMrvRoute
  '/ecosystem/digital-mrv-platforms': typeof EcosystemDigitalMrvPlatformsRoute
  '/ecosystem/energy-sector-intelligence': typeof EcosystemEnergySectorIntelligenceRoute
  '/ecosystem/energy-transition-workforce': typeof EcosystemEnergyTransitionWorkforceRoute
  '/ecosystem/in-house-agents': typeof EcosystemInHouseAgentsRoute
  '/ecosystem/project-development': typeof EcosystemProjectDevelopmentRoute
  '/ecosystem/rethink-carbon': typeof EcosystemRethinkCarbonRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/global-engagements': typeof GlobalEngagementsRoute
  '/impact': typeof ImpactRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ecosystem/advisory-house': typeof EcosystemAdvisoryHouseRoute
  '/ecosystem/agri-tech-solutions': typeof EcosystemAgriTechSolutionsRoute
  '/ecosystem/digital-mrv': typeof EcosystemDigitalMrvRoute
  '/ecosystem/digital-mrv-platforms': typeof EcosystemDigitalMrvPlatformsRoute
  '/ecosystem/energy-sector-intelligence': typeof EcosystemEnergySectorIntelligenceRoute
  '/ecosystem/energy-transition-workforce': typeof EcosystemEnergyTransitionWorkforceRoute
  '/ecosystem/in-house-agents': typeof EcosystemInHouseAgentsRoute
  '/ecosystem/project-development': typeof EcosystemProjectDevelopmentRoute
  '/ecosystem/rethink-carbon': typeof EcosystemRethinkCarbonRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/blog': typeof BlogIndexRoute
  '/what-we-do': typeof WhatWeDoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/global-engagements': typeof GlobalEngagementsRoute
  '/impact': typeof ImpactRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ecosystem/advisory-house': typeof EcosystemAdvisoryHouseRoute
  '/ecosystem/agri-tech-solutions': typeof EcosystemAgriTechSolutionsRoute
  '/ecosystem/digital-mrv': typeof EcosystemDigitalMrvRoute
  '/ecosystem/digital-mrv-platforms': typeof EcosystemDigitalMrvPlatformsRoute
  '/ecosystem/energy-sector-intelligence': typeof EcosystemEnergySectorIntelligenceRoute
  '/ecosystem/energy-transition-workforce': typeof EcosystemEnergyTransitionWorkforceRoute
  '/ecosystem/in-house-agents': typeof EcosystemInHouseAgentsRoute
  '/ecosystem/project-development': typeof EcosystemProjectDevelopmentRoute
  '/ecosystem/rethink-carbon': typeof EcosystemRethinkCarbonRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/about-us'
    | '/consulting'
    | '/contact'
    | '/global-engagements'
    | '/impact'
    | '/work-with-us'
    | '/blog/$slug'
    | '/ecosystem/advisory-house'
    | '/ecosystem/agri-tech-solutions'
    | '/ecosystem/digital-mrv'
    | '/ecosystem/digital-mrv-platforms'
    | '/ecosystem/energy-sector-intelligence'
    | '/ecosystem/energy-transition-workforce'
    | '/ecosystem/in-house-agents'
    | '/ecosystem/project-development'
    | '/ecosystem/rethink-carbon'
    | '/industries/$slug'
    | '/what-we-do/$slug'
    | '/blog/'
    | '/what-we-do/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/consulting'
    | '/contact'
    | '/global-engagements'
    | '/impact'
    | '/work-with-us'
    | '/blog/$slug'
    | '/ecosystem/advisory-house'
    | '/ecosystem/agri-tech-solutions'
    | '/ecosystem/digital-mrv'
    | '/ecosystem/digital-mrv-platforms'
    | '/ecosystem/energy-sector-intelligence'
    | '/ecosystem/energy-transition-workforce'
    | '/ecosystem/in-house-agents'
    | '/ecosystem/project-development'
    | '/ecosystem/rethink-carbon'
    | '/industries/$slug'
    | '/what-we-do/$slug'
    | '/blog'
    | '/what-we-do'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/about-us'
    | '/consulting'
    | '/contact'
    | '/global-engagements'
    | '/impact'
    | '/work-with-us'
    | '/blog/$slug'
    | '/ecosystem/advisory-house'
    | '/ecosystem/agri-tech-solutions'
    | '/ecosystem/digital-mrv'
    | '/ecosystem/digital-mrv-platforms'
    | '/ecosystem/energy-sector-intelligence'
    | '/ecosystem/energy-transition-workforce'
    | '/ecosystem/in-house-agents'
    | '/ecosystem/project-development'
    | '/ecosystem/rethink-carbon'
    | '/industries/$slug'
    | '/what-we-do/$slug'
    | '/blog/'
    | '/what-we-do/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  ConsultingRoute: typeof ConsultingRoute
  ContactRoute: typeof ContactRoute
  GlobalEngagementsRoute: typeof GlobalEngagementsRoute
  ImpactRoute: typeof ImpactRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  EcosystemAdvisoryHouseRoute: typeof EcosystemAdvisoryHouseRoute
  EcosystemAgriTechSolutionsRoute: typeof EcosystemAgriTechSolutionsRoute
  EcosystemDigitalMrvRoute: typeof EcosystemDigitalMrvRoute
  EcosystemDigitalMrvPlatformsRoute: typeof EcosystemDigitalMrvPlatformsRoute
  EcosystemEnergySectorIntelligenceRoute: typeof EcosystemEnergySectorIntelligenceRoute
  EcosystemEnergyTransitionWorkforceRoute: typeof EcosystemEnergyTransitionWorkforceRoute
  EcosystemInHouseAgentsRoute: typeof EcosystemInHouseAgentsRoute
  EcosystemProjectDevelopmentRoute: typeof EcosystemProjectDevelopmentRoute
  EcosystemRethinkCarbonRoute: typeof EcosystemRethinkCarbonRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  WhatWeDoSlugRoute: typeof WhatWeDoSlugRoute
  WhatWeDoIndexRoute: typeof WhatWeDoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-engagements': {
      id: '/global-engagements'
      path: '/global-engagements'
      fullPath: '/global-engagements'
      preLoaderRoute: typeof GlobalEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/': {
      id: '/what-we-do/'
      path: '/what-we-do'
      fullPath: '/what-we-do/'
      preLoaderRoute: typeof WhatWeDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/what-we-do/$slug': {
      id: '/what-we-do/$slug'
      path: '/what-we-do/$slug'
      fullPath: '/what-we-do/$slug'
      preLoaderRoute: typeof WhatWeDoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/rethink-carbon': {
      id: '/ecosystem/rethink-carbon'
      path: '/ecosystem/rethink-carbon'
      fullPath: '/ecosystem/rethink-carbon'
      preLoaderRoute: typeof EcosystemRethinkCarbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/project-development': {
      id: '/ecosystem/project-development'
      path: '/ecosystem/project-development'
      fullPath: '/ecosystem/project-development'
      preLoaderRoute: typeof EcosystemProjectDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/in-house-agents': {
      id: '/ecosystem/in-house-agents'
      path: '/ecosystem/in-house-agents'
      fullPath: '/ecosystem/in-house-agents'
      preLoaderRoute: typeof EcosystemInHouseAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/energy-transition-workforce': {
      id: '/ecosystem/energy-transition-workforce'
      path: '/ecosystem/energy-transition-workforce'
      fullPath: '/ecosystem/energy-transition-workforce'
      preLoaderRoute: typeof EcosystemEnergyTransitionWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/energy-sector-intelligence': {
      id: '/ecosystem/energy-sector-intelligence'
      path: '/ecosystem/energy-sector-intelligence'
      fullPath: '/ecosystem/energy-sector-intelligence'
      preLoaderRoute: typeof EcosystemEnergySectorIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/digital-mrv-platforms': {
      id: '/ecosystem/digital-mrv-platforms'
      path: '/ecosystem/digital-mrv-platforms'
      fullPath: '/ecosystem/digital-mrv-platforms'
      preLoaderRoute: typeof EcosystemDigitalMrvPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/digital-mrv': {
      id: '/ecosystem/digital-mrv'
      path: '/ecosystem/digital-mrv'
      fullPath: '/ecosystem/digital-mrv'
      preLoaderRoute: typeof EcosystemDigitalMrvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/agri-tech-solutions': {
      id: '/ecosystem/agri-tech-solutions'
      path: '/ecosystem/agri-tech-solutions'
      fullPath: '/ecosystem/agri-tech-solutions'
      preLoaderRoute: typeof EcosystemAgriTechSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/advisory-house': {
      id: '/ecosystem/advisory-house'
      path: '/ecosystem/advisory-house'
      fullPath: '/ecosystem/advisory-house'
      preLoaderRoute: typeof EcosystemAdvisoryHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  ConsultingRoute: ConsultingRoute,
  ContactRoute: ContactRoute,
  GlobalEngagementsRoute: GlobalEngagementsRoute,
  ImpactRoute: ImpactRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  EcosystemAdvisoryHouseRoute: EcosystemAdvisoryHouseRoute,
  EcosystemAgriTechSolutionsRoute: EcosystemAgriTechSolutionsRoute,
  EcosystemDigitalMrvRoute: EcosystemDigitalMrvRoute,
  EcosystemDigitalMrvPlatformsRoute: EcosystemDigitalMrvPlatformsRoute,
  EcosystemEnergySectorIntelligenceRoute:
    EcosystemEnergySectorIntelligenceRoute,
  EcosystemEnergyTransitionWorkforceRoute:
    EcosystemEnergyTransitionWorkforceRoute,
  EcosystemInHouseAgentsRoute: EcosystemInHouseAgentsRoute,
  EcosystemProjectDevelopmentRoute: EcosystemProjectDevelopmentRoute,
  EcosystemRethinkCarbonRoute: EcosystemRethinkCarbonRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  WhatWeDoSlugRoute: WhatWeDoSlugRoute,
  WhatWeDoIndexRoute: WhatWeDoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
